### ISSUE TITLE
[QUESTION] Store face attributes/embeddings?

### ISSUE THREAD

**Issue by thedevskie** [nonam4/react-native-vision-camera-face-detector#21]
Hi @nonam4 , first, thanks for this great library.
I have a question if this library is capable of storing the face attributes/embeddings into the database and compare it later on for a verification? e.g. I register my face first and then use it for unlocking the app if the scanned face is valid.

I have created a prototype where it detects the face if it is inside the face placeholder but stuck here at the moment.

Thank you

**Comment by nonam4** [comment]
Hello.

Yes, it's possible because you'll have all face's embeddings but I have no idea how you can achieve this using this library.
Maybe you can try looking for euclidean distance as a starting point.. 

But I don't think it's a good idea use client side to handle authentication, even worse if there's sensitive data in your app...
You should consider to send face data to backend and there you can compare stored face data, etc... 

In my project I use [vlad's face-api package](https://github.com/vladmandic/face-api) (I've also tested [human](https://github.com/vladmandic/human) but face-api works better in my case) as a backend comparision framework.

If helps, [here's](https://github.com/vladmandic/face-api/issues/175) a little contributing I've made...

I wish I could help you more but this is everything I can afford without any payment.

**Comment by thedevskie** [comment]
Hi @nonam4 , thanks for answering my question. I am still in the planning phase and doing more research on the best way to do it. Thanks for your reference links. I will take a look.

Cheers.
