### ISSUE TITLE
[BUG] App not working (crashing?!) on release build

### ISSUE THREAD

**Issue by Nurmehemmed** [nonam4/react-native-vision-camera-face-detector#43]
It doesnt work after build release apk and installed it on device

**Comment by quangnd1910** [comment]
Me, not work on ios too, on release build

**Comment by quangnd1910** [comment]
<img width="932" alt="image" src="https://github.com/nonam4/react-native-vision-camera-face-detector/assets/76483233/2820234d-89dd-4aab-bb5a-504f7a9144e1">
When I commented out runAsync, it worked

**Comment by nonam4** [comment]
The problem is in `react-native-worklets-core` context. On previous versions of it I could make a context creating workaround but on this new `1.1.1` version I can't do this anymore.

> When I commented out runAsync, it worked

Removing `runAsync` will work but on slower devices you'll notice fps drops on camera preview. 

I'll leave this issue open for now

**Comment by nonam4** [comment]
Please check `1.6.1` release

**Comment by Nurmehemmed** [comment]
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/60698528/94f43749-0d0d-4014-8de8-0fb4233e7424)
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/60698528/8ff85261-bfa9-4f50-bdf1-6b0a3714aa77)
![image](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/60698528/391c434e-01c2-431a-8a9f-0ba8282ad70c)
There are deprecated functions in your Camera.tsx component

**Comment by nonam4** [comment]
@Nurmehemmed did you checked release notes?

**Comment by Nurmehemmed** [comment]
Sorry, i updated dependencies. Now i get Camera mount error. Trying to fix that. 
Camera mount error [unknown/unknown: No supported surface combination is found for camera device - Id : 1.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.streamsharing.StreamSharingConfig@30d18ba, androidx.camera.core.impl.ImageAnalysisConfig@bf25e5, androidx.camera.core.impl.ImageCaptureConfig@827d0dc]]

**Comment by Nurmehemmed** [comment]
i found. it is about i used format={format} in Camera component. It works now after delete it. But i have not format anymore

**Comment by nonam4** [comment]
I can confirm that original problem was solved on `1.6.1` version as it's working on builded (also store published) apps.

**Comment by Nurmehemmed** [comment]
@nonam4 maybe you used outdated version of vision-camera (4.0.0-beta.11) in 1.6.1 and so we cant use implement vision-camera problems with your 1.6.1 package

**Comment by nonam4** [comment]
@Nurmehemmed you have wome options then:

- Use version `1.6.0`: This version uses the most recent vision-camera and worklets-core versions, but as you said: "it crashes after releasing app". You may want to try following the vision-camera documentation instead of the recommended method.
- Fix the package yourself: You can use `patch-package` to fix the issue. You can also open a PR with the fix, and you'll be credited for your contribution.
- Create your own face-detection package: This option is more complex than it seems.

I created this package for my own project, and it's working very well on my released (and also store published) app. I made it open-source because there weren't any other updated packages available with the same functionality.

Since the package is open-source, you can use my code in any way you want, and I don't expect any payment for its use. However, I cannot dedicate more time to fixing an issue for which I haven't received any compensation, especially after exploring all possible solutions myself.

As I said before, I opened [this](https://github.com/margelo/react-native-worklets-core/issues/173) issue on worklets-core repo. When it's solved I'll publish a new version with a fix.

**Comment by Nurmehemmed** [comment]
Sorry, I didn't want to hurt you) I appreciate your effort. Thanks!

**Comment by Sachin1116** [comment]
@Nurmehemmed @nonam4 can you please try with this changes in camera.tsx 
const cameraFrameProcessor = useFrameProcessor( ( frame ) => {
    'worklet'
    runAsync( frame, async () => {
      'worklet'
      const internal = frame as FrameInternal
      const faces = detectFaces( frame )

      // increment frame count so we can use frame on 
      // js side without frame processor getting stuck
      internal.incrementRefCount()
      try {
       await  runOnJs(
          faces,
          frame
        )
      } catch (error) {
        console.log("lib error=>", error)
      }finally{
        internal.decrementRefCount()
      }
      
   
      // .finally( () => {
      //   // finally decrement frame count so it can be dropped
      //   internal.decrementRefCount()
      // } )
    } )
  }, [ runOnJs ] )
  
  
"react-native-vision-camera": "^4.0.1",
"react-native-vision-camera-face-detector": "1.6.0",
"react-native-worklets-core": "1.1.1",

**Comment by nonam4** [comment]
@Sachin1116 did you test generating app APK and installing it on your device?

**Comment by Sachin1116** [comment]
yes its working fine in android

**Comment by nonam4** [comment]
What android version are you using and on wich devices did you tested?

**Comment by Sachin1116** [comment]
Android 13 and 14

**Comment by Nurmehemmed** [comment]
I checked it but doesnt work on prod in Samsung galaxy a22 (Android version 13)

**Comment by Sachin1116** [comment]
did you change library version
"react-native-vision-camera": "4.0.1",
"react-native-vision-camera-face-detector": "1.6.0"
"react-native-worklets-core": "1.1.1"

**Comment by Nurmehemmed** [comment]
Of course

**Comment by SantoshYadavSridix** [comment]
Same issue on my end. Production build not working on Redmi 12 5g (Android 14) and Other Android Phones Redmi, Realme, etc with Android 12, 13, 14. I have not tested on 11 and below.

**Comment by Nurmehemmed** [comment]
@SantoshYadavSridix check 1.6.1 version please. Problem solved there already. Please, dont forget to read release notes (You must change other dependency versions)

**Comment by luicfrr** [comment]
I just released `1.6.2` version 🥳🎉 It is using latest `vision-camera` and `worklets-core` and it's not crashing on release mode. Can you please test it and give me a feedback? Thanks
